---
name: Oneplay Server
version: 0.0.3
slug: oneplayserver
description: Oneplay TV Server
url: "https://github.com/jaroslavhykel/hassio-addons/tree/main/o2tvserver"
init: false
panel_icon: mdi:television
arch:
  - amd64
  - aarch64
host_network: true
webui: "http://[HOST]:[PORT:8082]/"
homeassistant_api: true
ports:
  8082/tcp: 8082
ports_description:
  8082/tcp: Oneplay TV Service
map:
  - share:rw
options:
  o2_username: null
  o2_password: null
  o2_deviceid: null
  o2_webserver_ip: http://127.0.0.1:8082
  share_epg: false
  interval_download_epg: 0
  day_epg_before: 1
  day_epg_after: 1
  debug: false
  system_packages: []
  init_commands: []
  args: ""
schema:
  o2_username: str
  o2_password: str
  o2_deviceid: str
  o2_webserver_ip: str
  share_epg: bool
  interval_download_epg: int
  day_epg_before: int
  day_epg_after: int
  debug: bool
  system_packages:
    - str?
  init_commands:
    - str?
  args: str?
